### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [CyberCRI/RedMetrics#9]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by drpepper** [comment]
It was called MIT-LICENSE.

I changed the to avoid the false-positives on your search ;)
